/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EncryptedLikeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addComment"
      | "addCommentLike"
      | "addLike"
      | "addReaction"
      | "categoryReactionCounts"
      | "commentCount"
      | "comments"
      | "confidentialProtocolId"
      | "createPost"
      | "getCategoryReactionCount"
      | "getComment"
      | "getCommentContentChunk"
      | "getCommentContentChunkCount"
      | "getCommentCount(uint256)"
      | "getCommentCount()"
      | "getLikeCount"
      | "getPost"
      | "getPostCount"
      | "getReactionCount"
      | "getUserReaction"
      | "hasUserReacted"
      | "postAuthors"
      | "postCount"
      | "posts"
      | "removeReaction"
      | "userReactions"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CommentAdded"
      | "CommentLiked"
      | "PostCreated"
      | "ReactionChanged"
      | "ReactionRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addComment",
    values: [
      BigNumberish,
      BigNumberish,
      BytesLike[],
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "addCommentLike",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addLike",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addReaction",
    values: [BigNumberish, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "categoryReactionCounts",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "commentCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "comments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createPost",
    values: [string, string, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getCategoryReactionCount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getComment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCommentContentChunk",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCommentContentChunkCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCommentCount(uint256)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCommentCount()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLikeCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPost",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPostCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getReactionCount",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserReaction",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasUserReacted",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "postAuthors",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "postCount", values?: undefined): string;
  encodeFunctionData(functionFragment: "posts", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "removeReaction",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userReactions",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addComment", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addCommentLike",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addLike", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addReaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "categoryReactionCounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "commentCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "comments", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createPost", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCategoryReactionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getComment", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCommentContentChunk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCommentContentChunkCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCommentCount(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCommentCount()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLikeCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPost", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPostCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReactionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserReaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasUserReacted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "postAuthors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "postCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "posts", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeReaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userReactions",
    data: BytesLike
  ): Result;
}

export namespace CommentAddedEvent {
  export type InputTuple = [
    commentId: BigNumberish,
    postId: BigNumberish,
    author: AddressLike,
    parentCommentId: BigNumberish
  ];
  export type OutputTuple = [
    commentId: bigint,
    postId: bigint,
    author: string,
    parentCommentId: bigint
  ];
  export interface OutputObject {
    commentId: bigint;
    postId: bigint;
    author: string;
    parentCommentId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CommentLikedEvent {
  export type InputTuple = [commentId: BigNumberish, liker: AddressLike];
  export type OutputTuple = [commentId: bigint, liker: string];
  export interface OutputObject {
    commentId: bigint;
    liker: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PostCreatedEvent {
  export type InputTuple = [
    postId: BigNumberish,
    author: AddressLike,
    content: string,
    category: string
  ];
  export type OutputTuple = [
    postId: bigint,
    author: string,
    content: string,
    category: string
  ];
  export interface OutputObject {
    postId: bigint;
    author: string;
    content: string;
    category: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReactionChangedEvent {
  export type InputTuple = [
    postId: BigNumberish,
    user: AddressLike,
    reactionType: BigNumberish
  ];
  export type OutputTuple = [
    postId: bigint,
    user: string,
    reactionType: bigint
  ];
  export interface OutputObject {
    postId: bigint;
    user: string;
    reactionType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReactionRemovedEvent {
  export type InputTuple = [postId: BigNumberish, user: AddressLike];
  export type OutputTuple = [postId: bigint, user: string];
  export interface OutputObject {
    postId: bigint;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EncryptedLike extends BaseContract {
  connect(runner?: ContractRunner | null): EncryptedLike;
  waitForDeployment(): Promise<this>;

  interface: EncryptedLikeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addComment: TypedContractMethod<
    [
      postId: BigNumberish,
      parentCommentId: BigNumberish,
      encryptedContentChunks: BytesLike[],
      contentProof: BytesLike,
      countInputEuint32: BytesLike,
      countInputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  addCommentLike: TypedContractMethod<
    [commentId: BigNumberish, inputEuint32: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  addLike: TypedContractMethod<
    [postId: BigNumberish, inputEuint32: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  addReaction: TypedContractMethod<
    [
      postId: BigNumberish,
      reactionType: BigNumberish,
      inputEuint32: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  categoryReactionCounts: TypedContractMethod<
    [arg0: BytesLike],
    [string],
    "view"
  >;

  commentCount: TypedContractMethod<[], [bigint], "view">;

  comments: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, string] & {
        author: string;
        postId: bigint;
        parentCommentId: bigint;
        timestamp: bigint;
        encryptedLikeCount: string;
      }
    ],
    "view"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  createPost: TypedContractMethod<
    [content: string, category: string, tags: string[]],
    [bigint],
    "nonpayable"
  >;

  getCategoryReactionCount: TypedContractMethod<
    [category: string],
    [string],
    "view"
  >;

  getComment: TypedContractMethod<
    [commentId: BigNumberish],
    [
      [string, bigint, bigint, bigint] & {
        author: string;
        postId: bigint;
        parentCommentId: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getCommentContentChunk: TypedContractMethod<
    [commentId: BigNumberish, index: BigNumberish],
    [string],
    "view"
  >;

  getCommentContentChunkCount: TypedContractMethod<
    [commentId: BigNumberish],
    [bigint],
    "view"
  >;

  "getCommentCount(uint256)": TypedContractMethod<
    [postId: BigNumberish],
    [string],
    "view"
  >;

  "getCommentCount()": TypedContractMethod<[], [bigint], "view">;

  getLikeCount: TypedContractMethod<[postId: BigNumberish], [string], "view">;

  getPost: TypedContractMethod<
    [postId: BigNumberish],
    [
      [string, string, string, string[], bigint] & {
        author: string;
        content: string;
        category: string;
        tags: string[];
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getPostCount: TypedContractMethod<[], [bigint], "view">;

  getReactionCount: TypedContractMethod<
    [postId: BigNumberish, reactionType: BigNumberish],
    [string],
    "view"
  >;

  getUserReaction: TypedContractMethod<
    [user: AddressLike, postId: BigNumberish],
    [bigint],
    "view"
  >;

  hasUserReacted: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  postAuthors: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  postCount: TypedContractMethod<[], [bigint], "view">;

  posts: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        bigint
      ] & {
        author: string;
        content: string;
        category: string;
        encryptedLikeCount: string;
        encryptedLoveCount: string;
        encryptedClapCount: string;
        encryptedCelebrateCount: string;
        encryptedIdeaCount: string;
        encryptedCommentCount: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  removeReaction: TypedContractMethod<
    [postId: BigNumberish, inputEuint32: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  userReactions: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addComment"
  ): TypedContractMethod<
    [
      postId: BigNumberish,
      parentCommentId: BigNumberish,
      encryptedContentChunks: BytesLike[],
      contentProof: BytesLike,
      countInputEuint32: BytesLike,
      countInputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addCommentLike"
  ): TypedContractMethod<
    [commentId: BigNumberish, inputEuint32: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addLike"
  ): TypedContractMethod<
    [postId: BigNumberish, inputEuint32: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addReaction"
  ): TypedContractMethod<
    [
      postId: BigNumberish,
      reactionType: BigNumberish,
      inputEuint32: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "categoryReactionCounts"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "commentCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "comments"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, string] & {
        author: string;
        postId: bigint;
        parentCommentId: bigint;
        timestamp: bigint;
        encryptedLikeCount: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createPost"
  ): TypedContractMethod<
    [content: string, category: string, tags: string[]],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getCategoryReactionCount"
  ): TypedContractMethod<[category: string], [string], "view">;
  getFunction(
    nameOrSignature: "getComment"
  ): TypedContractMethod<
    [commentId: BigNumberish],
    [
      [string, bigint, bigint, bigint] & {
        author: string;
        postId: bigint;
        parentCommentId: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCommentContentChunk"
  ): TypedContractMethod<
    [commentId: BigNumberish, index: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCommentContentChunkCount"
  ): TypedContractMethod<[commentId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCommentCount(uint256)"
  ): TypedContractMethod<[postId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getCommentCount()"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLikeCount"
  ): TypedContractMethod<[postId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getPost"
  ): TypedContractMethod<
    [postId: BigNumberish],
    [
      [string, string, string, string[], bigint] & {
        author: string;
        content: string;
        category: string;
        tags: string[];
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPostCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getReactionCount"
  ): TypedContractMethod<
    [postId: BigNumberish, reactionType: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserReaction"
  ): TypedContractMethod<
    [user: AddressLike, postId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasUserReacted"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "postAuthors"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "postCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "posts"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        bigint
      ] & {
        author: string;
        content: string;
        category: string;
        encryptedLikeCount: string;
        encryptedLoveCount: string;
        encryptedClapCount: string;
        encryptedCelebrateCount: string;
        encryptedIdeaCount: string;
        encryptedCommentCount: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "removeReaction"
  ): TypedContractMethod<
    [postId: BigNumberish, inputEuint32: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userReactions"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "CommentAdded"
  ): TypedContractEvent<
    CommentAddedEvent.InputTuple,
    CommentAddedEvent.OutputTuple,
    CommentAddedEvent.OutputObject
  >;
  getEvent(
    key: "CommentLiked"
  ): TypedContractEvent<
    CommentLikedEvent.InputTuple,
    CommentLikedEvent.OutputTuple,
    CommentLikedEvent.OutputObject
  >;
  getEvent(
    key: "PostCreated"
  ): TypedContractEvent<
    PostCreatedEvent.InputTuple,
    PostCreatedEvent.OutputTuple,
    PostCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ReactionChanged"
  ): TypedContractEvent<
    ReactionChangedEvent.InputTuple,
    ReactionChangedEvent.OutputTuple,
    ReactionChangedEvent.OutputObject
  >;
  getEvent(
    key: "ReactionRemoved"
  ): TypedContractEvent<
    ReactionRemovedEvent.InputTuple,
    ReactionRemovedEvent.OutputTuple,
    ReactionRemovedEvent.OutputObject
  >;

  filters: {
    "CommentAdded(uint256,uint256,address,uint256)": TypedContractEvent<
      CommentAddedEvent.InputTuple,
      CommentAddedEvent.OutputTuple,
      CommentAddedEvent.OutputObject
    >;
    CommentAdded: TypedContractEvent<
      CommentAddedEvent.InputTuple,
      CommentAddedEvent.OutputTuple,
      CommentAddedEvent.OutputObject
    >;

    "CommentLiked(uint256,address)": TypedContractEvent<
      CommentLikedEvent.InputTuple,
      CommentLikedEvent.OutputTuple,
      CommentLikedEvent.OutputObject
    >;
    CommentLiked: TypedContractEvent<
      CommentLikedEvent.InputTuple,
      CommentLikedEvent.OutputTuple,
      CommentLikedEvent.OutputObject
    >;

    "PostCreated(uint256,address,string,string)": TypedContractEvent<
      PostCreatedEvent.InputTuple,
      PostCreatedEvent.OutputTuple,
      PostCreatedEvent.OutputObject
    >;
    PostCreated: TypedContractEvent<
      PostCreatedEvent.InputTuple,
      PostCreatedEvent.OutputTuple,
      PostCreatedEvent.OutputObject
    >;

    "ReactionChanged(uint256,address,uint8)": TypedContractEvent<
      ReactionChangedEvent.InputTuple,
      ReactionChangedEvent.OutputTuple,
      ReactionChangedEvent.OutputObject
    >;
    ReactionChanged: TypedContractEvent<
      ReactionChangedEvent.InputTuple,
      ReactionChangedEvent.OutputTuple,
      ReactionChangedEvent.OutputObject
    >;

    "ReactionRemoved(uint256,address)": TypedContractEvent<
      ReactionRemovedEvent.InputTuple,
      ReactionRemovedEvent.OutputTuple,
      ReactionRemovedEvent.OutputObject
    >;
    ReactionRemoved: TypedContractEvent<
      ReactionRemovedEvent.InputTuple,
      ReactionRemovedEvent.OutputTuple,
      ReactionRemovedEvent.OutputObject
    >;
  };
}
